
name: pipeline

on:
  pull_request:
    branches: [dev]

permissions:
  contents: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: .env
        run: |
              cat <<EOF > .env
              APP_PORT=${{ secrets.APP_PORT }}
              DATABASE_URL=${{ secrets.DATABASE_URL }}
              JWT_SECRET=${{ secrets.JWT_SECRET }}
              AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
              AWS_REGION=${{ secrets.AWS_REGION }}
              EOF

      - uses: actions/setup-node@v3.9.1
        with:
          node-version: 22.x
      - name: setup
        run: npm ci
      - name: Unit tests
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.9.1
        with:
          node-version: 22.x
      - name: .env
        run: |
              cat <<EOF > .env
              APP_PORT=${{ secrets.APP_PORT }}
              DATABASE_URL=${{ secrets.DATABASE_URL }}
              JWT_SECRET=${{ secrets.JWT_SECRET }}
              AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
              AWS_REGION=${{ secrets.AWS_REGION }}
              EOF

      - name: setup
        run: npm ci
      - name: Lint
        run: npm run lint

  pipeline:
    needs:
      - unit-tests
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Dev
        run: echo "Dev Stage completed!"
